upstream webapp {
    server appseed_app:8000;  # O contêiner Django rodando na porta 8000
}

server {
    listen 80;  # Nginx escutando na porta padrão HTTP
    server_name 147.79.82.234 srv613709.hstgr.cloud;

    location / {
        proxy_pass http://webapp;  # Direciona para o upstream 'webapp'
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
